/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as Import } from './routes/_'
import { Route as IndexImport } from './routes/_/index'
import { Route as AuthDocumentsImport } from './routes/_auth/documents'
import { Route as RegisterImport } from './routes/_/register'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const Route = Import.update({
  id: '/_',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => Route,
} as any)

const AuthDocumentsRoute = AuthDocumentsImport.update({
  path: '/documents',
  getParentRoute: () => AuthRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '//register': {
      id: '//register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_auth/documents': {
      id: '/_auth/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthDocumentsImport
      parentRoute: typeof AuthImport
    }
    '//': {
      id: '//'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  Route: Route.addChildren({ RegisterRoute, IndexRoute }),
  AuthRoute: AuthRoute.addChildren({ AuthDocumentsRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "_.tsx",
      "children": [
        "//register",
        "//"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/documents"
      ]
    },
    "//register": {
      "filePath": "_/register.tsx",
      "parent": "/"
    },
    "/_auth/documents": {
      "filePath": "_auth/documents.tsx",
      "parent": "/_auth"
    },
    "//": {
      "filePath": "_/index.tsx",
      "parent": "/"
    }
  }
}
ROUTE_MANIFEST_END */
